version: '3.8'

services:
  # 1. The Express.js backend application service
  backend:
    # Replace with your actual ECR or Docker Hub backend repository URL
    image: 520557389723.dkr.ecr.eu-west-1.amazonaws.com/dev-backend:latest
    container_name: leavetrack_backend
    restart: always
    ports:
      - "8000:8000"
    # This loads all the DB_* and JWT_SECRET variables from the .env file on the host
    env_file:
      - .env

  # 2. The Vite/React frontend application service
  frontend:
    # Replace with your actual ECR or Docker Hub frontend repository URL
    image: 520557389723.dkr.ecr.eu-west-1.amazonaws.com/dev-frontend:latest
    container_name: leavetrack_frontend
    restart: always
    ports:
      # Changed host port to 80 so users can access it via standard HTTP without typing :8080
      - "80:80"
    depends_on:
      - backend

# Notice: The "db" service and "volumes" sections are completely removed 
# because AWS RDS manages your data storage externally!
